# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='auth',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
